version: "3"
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24
services:
  saja:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
