name: deploy-website

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make stage=prod build
      - run: make password=$DOCKER_PASSWORD login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: make stage=prod push
      - run: make logout
      - uses: appleboy/ssh-action@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.SERVER_PRIVATE_KEY_PASSPHRASE }}
          envs: DOCKER_PASSWORD
          script: |
            cd ~/frontend/
            make password=$DOCKER_PASSWORD login
            make pull
            make
            make logout
