name: deploy-website

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sajaweb/saja-react-prod
      # - uses: actions/checkout@v2
      # - run: make stage=prod build
      # - run: make password=$DOCKER_PASSWORD login
      #   env:
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # - run: make stage=prod push
      # - run: make logout
      - uses: appleboy/ssh-action@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.KEY_PASSPHRASE }}
          envs: DOCKER_PASSWORD
          script: |
            cd saja-web/
            make password=$DOCKER_PASSWORD login
            make pull
            make
            make logout
